### ISSUE TITLE
setShowHasSubClass

### ISSUE THREAD

**Issue by erraiva** [FriendsOfREDAXO/navigation_factory#10]
**setShowHasSubClass**
... scheint bei mir einen Fehler zu verursachen. Frische Installation, 
Hoster ist HostEurope mit 
REDAXO | 5.11.0
PHP 7.3.18-he10.1
MySQL 5.7.30.
Es wird keine li-Klasse für das Dropdown erzeugt. Im Systemlog gibt es Warnings:
```
Warning 	Invalid argument supplied for foreach() 	
redaxo/src/addons/navigation_factory/lib/rex_nav_simple_html_dom.php
	651
Warning 	preg_match_all(): Compilation failed: invalid range in character class at offset 4 	
redaxo/src/addons/navigation_factory/lib/rex_nav_simple_html_dom.php
	644
```

**Comment by webregie** [comment]
Hab ich auch. Es gibt ein merge. Aber ich weiß nicht ob @alxndr-w das macht...

**Comment by schuer** [comment]
@darwin26 hat bereits einen PR bereitgestellt, der das Problem beheben sollte: #11
