### ISSUE TITLE
Update für rex_nav_simple_html_dom.php?

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/navigation_factory#12]
Die **rex_nav_simple_html_dom.php** ist ja eine von Sourgeforge importierte Klasse eines anderen Autor, die mit V1.5 von 2012 in das Addon gewandert ist. Nicht 1 zu 1, sondern mit ein paar kleineren Umbenennungen (Klassen fangen mit rex_ an und drei Funktionen sind zu static-Function in einer der Klassen geworden. 

Es gibt eine Version 1.9.1. von November 2019. (und danach noch zwei 2.0-RC), also 7 Jahre weiter mit zahlreichen Bugfixes

Da die Version im Addon Ende 2020 Updates erfahren hat wäre meine Frage, wie ihr zu einem Update auf die 1.9.1 steht?

**Comment by skerbis** [comment]
Leg los. Und falls möglich solche classes über composer aktualisieren

**Comment by skerbis** [comment]
composer require simplehtmldom/simplehtmldom

**Comment by christophboecker** [comment]
rexdude hat damals den Code von simplehtmldom modifiziert (Klassen umbenannt, freistehende Funktionen in eine der Klassen integriert, Referenzen entsprechend angepasst). Kann mir nicht vorstellen, dass composer den Code umbaut.

**Comment by skerbis** [comment]
Was macht dieses AddOn anders als andere Lösungen? Macht es Sinn die Class wieder reinzufriemeln und zu ändern?
Soweit ich das erkennen kann macht es nichts anderes als die aktuelle redaxo factory

**Comment by christophboecker** [comment]
Nach meinem Eindruck ist die redaxo factory etwas kniffeliger zu justieren und in Sachen classes arg geschwätzig. Geschmackssache. 

Das Problem ist wohl auch, dass die V 1.5 im Addon ein paar Änderungen (Feherkorrekturen?) bekommen hat, die auch in der neueren V 1.9 nachgezogen werden müssten. Will man sich wirklich die Mühe machen? Grundmodifikationen sind schnell gemacht, hab ich schon vorliegen. Aber der Rest? Wenn es nicht sein muss - und ich habe den Eindruck es muss nicht ....

**Comment by skerbis** [comment]
Grundsätzlich sehe ich es problematisch für die spätere Pflege an vendor classes zu modifizieren. Liesse es sich nicht über eine abgeleitete class mit extend realisieren?  Aus meiner Sicht wäre es ein Fehler so fortzufahren. Aber gut ich nutze es nicht. Ist nur meine Einschätzung

**Comment by christophboecker** [comment]
Seit 23 Minuten ist es mir auch egal; hab es eben rausoperiert und lebe jetzt mit der redaxo-internen Navi. Ich würde mir unter Würdigung der Gesamtumstände die Arbeit nicht mehr machen, hier was anzupassen.
