### ISSUE TITLE
Meldung bei PHP 8.1

### ISSUE THREAD

**Issue by erraiva** [FriendsOfREDAXO/navigation_factory#13]
bei PHP 8.1 erscheint folgende Meldung:
Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in redaxo/src/addons/navigation_factory/lib/rex_nav_simple_html_dom.php on line 665

REDAXO 5.14.1

LG Heinz

**Comment by erraiva** [comment]
Kommt wohl nur im Zusammenhang mit PHP Apache vor, bei PHP nginx ist die Meldung nicht.

**Comment by erraiva** [comment]
Der Hinweis verschwindet, wenn in Zeile 665 ein (string) vor die $key-Variable gestellt wird:
$key=strtolower((string)$key);

**Comment by AWqxKAWERbXo** [comment]
closed in https://github.com/FriendsOfREDAXO/navigation_factory/commit/82daf87674783477df0dab86089fa7c60b15e3bb

Danke @rotzek für die Beauftragung
