### ISSUE TITLE
'has-sub' funktioniert nicht mehr

### ISSUE THREAD

**Issue by elektromanager** [FriendsOfREDAXO/navigation_factory#4]
Folgende Parameter funktionieren nicht mehr:

$nav->setShowHasSubClass(true); // zeigt 'has-sub' klasse für die li an
$nav->setHasSubClass('has-sub'); // klassenname der 'has-sub' klasse

Alles was man dort konfiguriert wird bei der Ausgabe ignoriert.

**Comment by webregie** [comment]
Du hast sicher PHP 7.3 aktiviert? Unter 7.2 geht es noch. 
Aber schau mal unter Pull requests. Da hat schon @Krisse85 etwas eingebaut. Die rex_nav_simple_html_dom.php kannst du verwenden. Damit geht es auch unter 7.3.

Warum das Update nicht eingebunden wird, weiß ich nicht.

**Comment by elektromanager** [comment]
Ja ich habe PHP 7.3 aktiviert. Ich werde die rex_nav_simple_html_dom.php mal runterladen. Danke für die schnelle Reaktion!
